import { pngHexToDataUrl } from '../pngHex.ts'
import hex0 from './chili-portrait.hex.00.ts'
import hex1 from './chili-portrait.hex.01.ts'
import hex2 from './chili-portrait.hex.02.ts'
import hex3 from './chili-portrait.hex.03.ts'
import hex4 from './chili-portrait.hex.04.ts'
import hex5 from './chili-portrait.hex.05.ts'
import hex6 from './chili-portrait.hex.06.ts'
import hex7 from './chili-portrait.hex.07.ts'
import hex8 from './chili-portrait.hex.08.ts'
import hex9 from './chili-portrait.hex.09.ts'
import hex10 from './chili-portrait.hex.10.ts'
import hex11 from './chili-portrait.hex.11.ts'
import hex12 from './chili-portrait.hex.12.ts'
import hex13 from './chili-portrait.hex.13.ts'
import hex14 from './chili-portrait.hex.14.ts'
import hex15 from './chili-portrait.hex.15.ts'
import hex16 from './chili-portrait.hex.16.ts'

export default pngHexToDataUrl([hex0, hex1, hex2, hex3, hex4, hex5, hex6, hex7, hex8, hex9, hex10, hex11, hex12, hex13, hex14, hex15, hex16].join(''))
